name: omega
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy>=2.0,<3
  - pandas>=2.2,<3
  - scipy>=1.14,<2
  - matplotlib>=3.9,<4
  - openpyxl>=3.1,<4
  - pybaselines>=1.2,<2
  - lmfit>=1.3,<2
  - pyopenms>=3.2,<4
